### ISSUE TITLE
Confused about PyTyDefects

### ISSUE THREAD

**Issue by QingyuanLi1211** [sola-st/PyTy#1]
Hi, this awesome work. I have a question for you: when using pyty_predict.py to predict a type error, the data format used is
{
  "rule_id": "Unbound name [10]",
  "message": " Name `y_test` is used but not defined in the current scope.",
  "warning_line": "    results = mean_squared_error(y_test, model.predict(X_test))",
  "source_code": "    # Run some test predictions\n    results = mean_squared_error(y_test, model.predict(X_test))\n"
}
But the json file data format in Inputs.zip seems to be more complex and has more defects than the 2,766 claimed by PyTyDefects in the paper. So, if I want to use PyTyDefects for LLM bug fixing, what should I use from the json file?
Also, I'm confused about the contents of "warning_line" and the contents of "source_code" in the value of "min_patch", which one is the line of bug code and which one is the context of the bug code? Looking forward to your reply!

**Comment by luca-digrazia** [comment]
Hi, thank you!

Let me answer your questions:

1. The JSON files contain many more fields. However, the model uses only some of them. In the example, we show the main fields to be more concise.
2. The initial dataset collected consisted of over 11k bugs. We used a subset of it that fits the requirements of our model using the following filters:

```
"min_patch_found": true,
"single_hunk": true,
"fit_TFix": true,
```

4. "warning_line_no" is the absolute line number relative to the full file "filename"
5. "source_code" contains the line with the bug and the context (up to 3 lines) because it is what our model could handle. If you need extra context, you can clone the "project",  checkout the "commit", open "filename" and get more code around "warning_line_no"
6. Finally, in the folder output/, you will find the baseline we used for our evaluation. If you want to compare your model with ours, you can load that JSON and run the same experiment we ran for our evaluation.

Let me know if you have more questions. Thanks.

**Comment by QingyuanLi1211** [comment]
Thank you very much for your answer and for providing such an excellent dataset. I will ask you again if I have any questions, thanks again!

**Comment by QingyuanLi1211** [comment]
Hello, another question here. In pyty_testing.py, you have used trainer.predict() and model.generate() for generation respectively. If I use an LLM, can I all use model.generate() uniformly. Are you using trainer.predict() because you are using your own fine-tuned model? thanks a lot~

**Comment by luca-digrazia** [comment]
We are using trainer.predict() to fine-tune a T5 model that was already trained to fix Javascript errors ([T-fix paper](https://files.sri.inf.ethz.ch/website/papers/icml21-tfix.pdf)). I think you can use it for your case, adapting a little the code in model.generate().

**Comment by QingyuanLi1211** [comment]
ok, I got it. Thanks, a lot!!
